export const ANONYMIZED_FEW_SHOT_EXAMPLES = `
EXEMPLO DE REFERÊNCIA DE ESTILO - MODO EMERGÊNCIA / UTI (Apenas para aprender a formatação, NÃO copie dados clínicos):

#LISTA DE PROBLEMAS:
P1. FRAQUEZA EM MID E DESEQUILÍBRIO + PICO PRESSÓRICO (PA 263X137)
    SD1: AVC FORA DE JANELA
    SD2: URGÊNCIA HIPERTENSIVA
P2. HAS E DM2
P3. MÁ ADESÃO MEDICAMENTOSA

#HMA:
PACIENTE COM HISTÓRICO DE HAS E DM, DÁ ENTRADA EM SALA VERMELHA COM QUEIXA DE PARESTESIA EM MMII E INCOORDENAÇÃO HÁ 8 HORAS. NÍVEIS PRESSÓRICOS ELEVADOS (263X137). NEGA CEFALEIA, VERTIGEM OU DISARTRIA. INICIADO NITROPRUSSIATO DE SÓDIO EM BOMBA DE INFUSÃO CONTÍNUA A 10 ML/H.

#AM:
HAS E DM INSULINO-REQUERENTE. NEGA CIRURGIAS PRÉVIAS.

#MUC:
USO REGULAR: LOSARTANA 50MG (1-0-1) | INSULINA NPH (20-0-14). USO IRREGULAR: ANLODIPINO 5MG (0-0-2) | METFORMINA 850MG (1-1-1).

#ALERGIAS:
NEGA ALERGIAS CONHECIDAS.

#EXAME FÍSICO ADMISSONAL:
A: VA PÉRVIA. TRAQUEIA CENTRALIZADA.
B: MVBD SEM RA. SAT 98% EM AA.
C: BRNF EM 2T. TEC <3S. PA 210X110 MMHG.
D: ECG 15, PIFR. SEM SINAIS MENÍNGEOS. FORÇA GRAU 4 EM MID. NIHSS 2.
E: SEM LESÕES OU TRAUMAS. EXTREMIDADES AQUECIDAS.

#EVOLUÇÃO 06/10 SD:
GERAL: REG, ANICTÉRICA, ACIANÓTICA, PESO ESTIMADO 80KG.
NEURO: ALERTA, ORIENTADA, PIFR, DÉFICIT MOTOR EM MID (FORÇA IV). SEM CRISES NO PERÍODO.
AR: EXPONTÂNEA EM AA, EUPNEICA, MVBD SEM RA.
ACV: ESTÁVEL EM NIPRIDE 8ML/H, NORMOCÁRDICA, BRNF SEM SOPROS.
TGI: DIETA BRANDA HIPOSSÓDICA COM BOA ACEITAÇÃO. ABDOME FLÁCIDO E INDOLOR.
R/M: DIURESE PRESENTE, FUNÇÃO RENAL PRESERVADA.
H/I: HB ESTÁVEL, AFEBRIL SEM ATB.
EXT: BEM PERFUNDIDAS, SEM EDEMAS.

#EXAMES COMPLEMENTARES:
> LABORATÓRIO:
LAB (05/10): HB 12,1 | HT 38,4 | LEUCO 6.000 | PLAQ 192.000 | UR 30,6 | CR 0,91 | NA 134,5 | K 3,79 | TGO 25 | TGP 10

#CONDUTAS:
REGULAÇÃO PARA TC DE CRÂNIO E AVALIAÇÃO NEUROLÓGICA // AMB AVANÇADA
VIGILÂNCIA CLÍNICA E HEMODINÂMICA:
MANTENHO NITROPRUSSIATO DE SÓDIO EM BOMBA
VIGIAR NÍVEIS PRESSÓRICOS E DÉFICITS FOCAIS
RECONCILIAÇÃO MEDICAMENTOSA DE ANTI-HIPERTENSIVOS E INSULINA
`;
