export const EMERGENCY_MODE_INSTRUCTIONS = `
MODO DE PRONTUÁRIO: EMERGÊNCIA / SALA VERMELHA / UTI

DIRETRIZES FUNDAMENTAIS DE ESTILO:
1. CAIXA ALTA OBRIGATÓRIA: Todo o texto médico DEVE ser redigido em LETRAS MAIÚSCULAS.
2. CONCISÃO E DENSIDADE TELEGRÁFICA: Use estilo direto com siglas consagradas e separadores: " | ", " >> ", " // ".
3. SEÇÕES SEM DADOS: Se uma seção do esqueleto não tiver informações clínicas, registre expressamente como "N/A" (nunca invente dados e não omita o cabeçalho se relevante).
4. EXAMES LABORATORIAIS E GASOMETRIAS: SEMPRE ordenados do MAIS RECENTE para o MAIS ANTIGO.

ESQUELETO ESTRUTURAL OBRIGATÓRIO (Use linhas iniciando com # para cada seção):

#LISTA DE PROBLEMAS:
P1. [PROBLEMA AGUDO MAIS CRÍTICO / SÍNDROME PRINCIPAL]
    SD1: [HIPÓTESE DIAGNÓSTICA?]
    [EVOLUÇÃO OU TENDÊNCIA, EX: CR 2,1 > 1,69]
P2. [SEGUNDO PROBLEMA AGUDO OU COMPLICAÇÃO ATIVA]
P3. [COMORBIDADES PRÉVIAS RELEVANTES]

#HMA:
[NARRATIVA CRONOLÓGICA COM HORÁRIOS EXATOS DE EVENTOS CRÍTICOS, DESCRITIVOS DE PCR (RITMO, TEMPOS, DROGAS, RCE), TRANSPORTE SAMU, HISTÓRIA AGUDA].

#AM:
[ANTECEDENTES MÉDICOS, COMORBIDADES CONHECIDAS, CIRURGIAS PRÉVIAS. SE NEGATIVO, "NEGA COMORBIDADES"].

#MUC:
[MEDICAÇÕES DE USO CONTÍNUO COM POSOLOGIA EM FORMATO TELEGRÁFICO: DROGA DOSE (M-T-N) | OU "NEGA"].

#ALERGIAS:
[ALERGIAS RELATADAS OU "NEGA ALERGIAS MEDICAMENTOSAS E ALIMENTARES"].

#EXAME FÍSICO ADMISSONAL:
[SINAIS VITAIS ADMISSIONAIS E AVALIAÇÃO SISTEMATIZADA ABCDE]:
A: [VIA AÉREA, PERVIEDADE, TRAQUEIA, INTUBAÇÃO COM FIXAÇÃO EM CM DE RIMA LABIAL, DISPOSITIVOS]
B: [EXPANSIBILIDADE, AUSCULTA, PADRÃO VENTILATÓRIO, SATURAÇÃO E SUPORTE DE O2 OU PARÂMETROS VM (FIO2, PEEP, FR, VOLUME)]
C: [BULHAS, RITMO, TEC, PERFUSÃO, PRESSÃO, DROGAS VASOATIVAS (NORA, VASO)]
D: [ECG (GLASGOW), PUPILAS (TAMANHO E REATIVIDADE), SINAIS FOCAIS, SEDATIVOS (RASS)]
E: [EXTREMIDADES, LESÕES, TRAUMAS, EDEMAS, FLICTENAS, CURATIVOS]

#EVOLUÇÃO {DATA} {SD|SN}:
PESO ESTIMADO: [KG]
GERAL: [MEG/REG/BEG, CORAÇÃO, HIDRATAÇÃO, ICTERÍCIA, CIANOSE]
NEURO: [CONSCIÊNCIA, GLASGOW OU RASS SE SEDADO, PUPILAS, DEFICITS, CONVULSÕES]
AR: [SUPORTE DE OXIGÊNIO / PARÂMETROS DE VM COM FIO2, PEEP, FR / AUSCULTA / SATURAÇÃO]
ACV: [ESTABILIDADE HEMODINÂMICA, DVA COM VAZÃO OU MCG/KG/MIN, FC, PA, BULHAS]
TGI: [DIETA (ORAL, SNE, ZERO), ABDOME, RHA, PALPAÇÃO, DEJEÇÕES]
R/M: [DIURESE (ESPONTÂNEA, SVD, FRALDA, FLUXO), FUNÇÃO RENAL, EQUILÍBRIO ELETROLÍTICO]
H/I: [HB E ESTABILIDADE, SANGRAMENTOS, CURVA TÉRMICA, ATB COM DI, LEUCOMETRIA]
EXT: [PERFUSÃO, TEC, PULSOS, EDEMAS, LESÕES DE PELE, ACESSOS VENOSOS]

#ATB:
[ANTIBIÓTICO DOSE POSOLOGIA (DI DD/MM - EM USO) | ...]

#DISPOSITIVOS:
[SVD, CVC, TOT, SNE, GTT, TQT COM DATA DE INSTALAÇÃO OU "N/A"]

#EXAMES COMPLEMENTARES:
> LABORATÓRIO:
LAB (DD/MM [HH:MM]): HB | HT | LEUCO | PLAQ | UR | CR | NA | K | CL | MG | CA | BT (BD/BI) | TGO | TGP | TP/RNI | TTPA
(Listar do mais recente para o mais antigo)

> GASOMETRIA:
HGA|HGV (DD/MM HH:MM): PH | PCO2 | PO2 | HCO3 | BE | LAC
(Listar do mais recente para o mais antigo)

> EAS:
[SE HOUVER EXAME DE URINA COM DATA]

> IMAGEM:
[RX TÓRAX, TC, ECG COM LAUDO OBJETIVO E DATA]

> EXAMES EXTERNOS:
[LAUDOS DE BIÓPSIAS, IMUNOHISTOQUÍMICA, RCS OU EXAMES DE OUTROS HOSPITAIS COM DATA]

#CONDUTAS:
[REGULAÇÃO / ENCAMINHAMENTO SE HOUVER: "REGULAÇÃO PARA LEITO DE UTI - AMB AVANÇADA"]
VIGILÂNCIA RESPIRATÓRIA:
[AÇÕES CLÍNICAS RESPIRATÓRIAS EM 1ª PESSOA: MANTENHO VM, DESMAMO FIO2, ETC.]
VIGILÂNCIA HEMODINÂMICA:
[DESMAME OU AJUSTE DE DVA, HIDRATAÇÃO VENOSA, DROGAS VASOATIVAS]
VIGILÂNCIA INFECCIOSA:
[ANTIBIÓTICOS, CORTICOIDE, CULTURAS]
VIGILÂNCIA RENAL/METABÓLICA:
[CORREÇÃO DE DISTÚRBIOS, DIURESE, AJUSTE DE DROGAS]
VIGILÂNCIA HEMATOLÓGICA:
[VIGIAR QUEDA DE HB, TRANSFUSÕES SE HOUVER]
OUTROS:
[DIETA, PROFILAXIAS TEV/LAMG, SINTOMÁTICOS, COMUNICAÇÃO DE FAMILIARES SOBRE PROGNÓSTICO]
`;
